version: '3.1'
services:

  certbot:
    image: certbot/dns-cloudflare
    network_mode: "host"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./cf_credentials.ini:/root/cloudflare.ini
    command: >
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 20
      --email ${LE_EMAIL}
      --agree-tos --no-eff-email
      --non-interactive
      -d ${HOST_NAME}
      -d www.${HOST_NAME} ${OTHER_HOST_NAMES}
      
  web:
    image: odoo:${ODOO_TAG}
    restart: always
    ports:
      - "127.0.0.1:8069:8069"
    environment:
      - HOST=${DB_HOST}
      - USER=odoo
      - PASSWORD=${ODOO_DB_PASS}
    command:  --db_sslmode verify-full
    volumes:
      - web-data:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/backups:/mnt/backups
      - ./odoo/enterprise:/mnt/enterprise
#      - ./certs/live/${HOST_NAME}/fullchain.pem:/var/lib/odoo/.postgresql/root.crt
#      - /etc/ssl/certs/ca-certificates.crt:/var/lib/odoo/.postgresql/root.crt
      - ./certs/ca-certificates.crt:/var/lib/odoo/.postgresql/root.crt

  nginx-proxy:
    image: nginx
    depends_on:
      certbot:
        condition: service_completed_successfully
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt 
      - ./templates:/etc/nginx/templates
    environment:
      - VIRTUAL_HOST_P=${HOST_NAME}
      - VIRTUAL_PORT_ODOO=8069
      - VIRTUAL_PORT_ODOOCHAT=8072
      - ORIGIN_HOST=web

volumes:
  web-data:

